"""Compatibility exports for relocated typed application events."""

from yoyopod.audio.music.models import Track
from yoyopod.communication.models import CallState, RegistrationState
from yoyopod.core.events import (
    CallEndedEvent,
    CallStateChangedEvent,
    IncomingCallEvent,
    LifecycleEvent,
    MusicAvailabilityChangedEvent,
    NetworkGpsFixEvent,
    NetworkGpsNoFixEvent,
    NetworkModemReadyEvent,
    NetworkPppDownEvent,
    NetworkPppUpEvent,
    NetworkRegisteredEvent,
    NetworkSignalUpdateEvent,
    PlaybackStateChangedEvent,
    RecoveryAttemptCompletedEvent,
    RegistrationChangedEvent,
    ScreenChangedEvent,
    StateChangedEvent,
    TrackChangedEvent,
    UserActivityEvent,
    VoIPAvailabilityChangedEvent,
)

__all__ = [
    "CallState",
    "CallEndedEvent",
    "CallStateChangedEvent",
    "IncomingCallEvent",
    "LifecycleEvent",
    "MusicAvailabilityChangedEvent",
    "NetworkGpsFixEvent",
    "NetworkGpsNoFixEvent",
    "NetworkModemReadyEvent",
    "NetworkPppDownEvent",
    "NetworkPppUpEvent",
    "NetworkRegisteredEvent",
    "NetworkSignalUpdateEvent",
    "PlaybackStateChangedEvent",
    "RecoveryAttemptCompletedEvent",
    "RegistrationState",
    "RegistrationChangedEvent",
    "ScreenChangedEvent",
    "StateChangedEvent",
    "Track",
    "TrackChangedEvent",
    "UserActivityEvent",
    "VoIPAvailabilityChangedEvent",
]
