[sip]
sip_port=-1
sip_tcp_port=-1
sip_tls_port=-1
register_only_when_network_is_up=1
register_only_when_upnp_is_ok=0
guess_hostname=1
inc_timeout=30
in_call_timeout=0
delayed_timeout=4
use_info=0
use_rfc2833=1
record_aware=0
media_encryption=srtp
verify_server_certs=1
verify_server_cn=1
auto_send_ringing=1
supported=replaces, outbound, gruu, path
user_agent=YoyoPod/1.0
refresh_window=90-90
linphone_specs=lime

[rtp]
audio_rtp_port=7076-7100
video_rtp_port=9076-9100
audio_jitt_comp=60
video_jitt_comp=60
nortp_timeout=30
audio_adaptive_jitt_comp_enabled=1
video_adaptive_jitt_comp_enabled=1
text_rtp_port=-1
nortp_onhold_timeout=3600

[net]
download_bw=380
upload_bw=60
adaptive_rate_control=1
mtu=1300

[sound]
echocancellation=1
ec_tail_len=200
ec_delay=50
ec_framesize=128
echolimiter=1
el_type=mic
el_thres=0.02
el_force=10
el_sustain=100
mic_gain_db=24.000000
playback_gain_db=3.600000
ng_thres=0.02
ng_floorgain=0.005
disable_record_on_mute=0

[misc]
empty_chat_room_deletion=1

[app]
auto_download_incoming_files_max_size=-1
auto_download_incoming_voice_recordings=1
auto_download_incoming_icalendars=1
sender_name_hidden_in_forward_message=0
record_aware=0

[video]
capture=0
display=0
show_local=0
size=vga
codec_priority_policy=1

[audio_codec_0]
mime=opus
rate=48000
channels=2
enabled=1
recv_fmtp=useinbandfec=1

[audio_codec_1]
mime=speex
rate=16000
channels=1
enabled=1
recv_fmtp=vbr=on

[audio_codec_2]
mime=speex
rate=8000
channels=1
enabled=1
recv_fmtp=vbr=on

[audio_codec_3]
mime=PCMU
rate=8000
channels=1
enabled=1

[audio_codec_4]
mime=PCMA
rate=8000
channels=1
enabled=1

[audio_codec_5]
mime=GSM
rate=8000
channels=1
enabled=0

[audio_codec_6]
mime=G722
rate=8000
channels=1
enabled=0

[audio_codec_7]
mime=G729
rate=8000
channels=1
enabled=1
recv_fmtp=annexb=yes

[audio_codec_8]
mime=speex
rate=32000
channels=1
enabled=0
recv_fmtp=vbr=on
